loki:
  image:
    tag: "2.9.3"
  service:
    type: LoadBalancer
    nodePort:
    port: 3100
    annotations:
      service.beta.kubernetes.io/alibaba-cloud-loadbalancer-address-type: "intranet"
    labels: {}
    targetPort: http-metrics

promtail:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
