apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []
helmCharts:
  - name: vault
    releaseName: vault-unseal
    repo: https://helm.releases.hashicorp.com
    valuesFile: values.yaml
    version: x.x.x
    namespace: guardian

replicas:
  - name: vault-unseal
    count: 0
